***
CREATE TABLE IF NOT EXISTS `errorlog` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `BATCHID` bigint(20) unsigned NOT NULL,
  `OBJECTTYPE` varchar(60) NOT NULL,
  `OBJECTNAME` varchar(60) NOT NULL,
  `COMMANDTYPE` varchar(60) NOT NULL,
  `COMMANDSTRING` varchar(8000) DEFAULT NULL,
  `DBCODE` char(15) NOT NULL,
  `CREATED_USER` char(15) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `MODIFIED_USER` char(15) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2127 DEFAULT CHARSET=latin1

***

ALTER TABLE DBINFO ADD CREATED_USER CHAR(15) DEFAULT NULL AFTER NEXT_BATCHID,
 ADD CREATED_DATE DATETIME AFTER CREATED_USER,
 ADD MODIFIED_USER CHAR(15) DEFAULT NULL AFTER CREATED_DATE,
 ADD MODIFIED_DATE TIMESTAMP AFTER MODIFIED_USER
 
 ***
 
 ALTER TABLE REPLICATIONLOG 
 ADD MODIFIED_USER CHAR(15) DEFAULT NULL AFTER CREATED_DATE,
 ADD MODIFIED_DATE TIMESTAMP AFTER MODIFIED_USER
 
 ***
 DROP TRIGGER IF EXISTS `TR_ERRORLOG_INSERT`;
CREATE DEFINER=root TRIGGER `TR_ERRORLOG_INSERT` BEFORE INSERT ON `ERRORLOG`
FOR EACH ROW
BEGIN
  SET NEW.CREATED_USER = DBUSER();
  SET NEW.CREATED_DATE = NOW();
END

***